# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Upload Python Package

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
    tags-ignore:
      - '**'
  workflow_dispatch:
    inputs:
      release:
        description: Publish a Release
        required: false
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          pipx install poetry
          poetry install
          poetry build

      - name: Publish to PyPI
        if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.release == 'true') || contains(github.event.head_commit.message, '[release]') }}
        env:
            POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
